config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  d_config:
    src: config/awesome/config
    dst: ~/.config/awesome/config
  d_evil:
    src: config/awesome/evil
    dst: ~/.config/awesome/evil
  f_rc.lua:
    src: config/awesome/rc.lua
    dst: ~/.config/awesome/rc.lua
  d_ui:
    src: config/awesome/ui
    dst: ~/.config/awesome/ui
  d_wallpapers:
    src: config/awesome/wallpapers
    dst: ~/.config/awesome/wallpapers
  f_config.conf:
    src: config/neofetch/config.conf
    dst: ~/.config/neofetch/config.conf
  f_oh-my-zsh.sh:
    src: config/oh-my-zsh/oh-my-zsh.sh
    dst: ~/.config/oh-my-zsh/oh-my-zsh.sh
  f_helpers.lua:
    src: config/awesome/helpers.lua
    dst: ~/.config/awesome/helpers.lua
  d_icons:
    src: config/awesome/icons
    dst: ~/.config/awesome/icons
  f_theme.lua:
    src: config/awesome/theme.lua
    dst: ~/.config/awesome/theme.lua
profiles:
  PC0:
    dotfiles:
    - f_zshrc
    - f_gitconfig
    - f_alacritty.yml
    - d_config
    - d_evil
    - f_rc.lua
    - d_ui
    - d_wallpapers
    - f_config.conf
    - f_oh-my-zsh.sh
    - f_helpers.lua
    - d_icons
    - f_theme.lua
