-- require("config.notifications")
require("config.settings")
require("config.cache")
require("config.wallpaper")
require("config.layout")
require("config.rules")
require("config.tags")
require("config.keys")