require("config.settings")
require("config.cache")
require("config.tags")
require("config.wallpaper")
require("config.layout")
require("config.rules")
require("config.keys")
require("config.signals")
